<a href="https://colab.research.google.com/github/saransh437/Python_practice/blob/main/Advance_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Introduction to numpy:
# this is an open-source library of python and this is used for the
# scientific calculations.
# list is hetrogeneous data type and numpy is homogeneuos data type

In [ ]:
a= [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
import numpy as np
a = np.array([1,2,3])
a*3

array([3, 6, 9])

In [ ]:
a=[1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [ ]:
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print('total shape',b.shape)   ###  shape = row,column
print('Total Element',b.size)  ###  size = row*column
print('Total Dimension',b.ndim) ### total dimension = 2

total shape (3, 3)
Total Element 9
Total Dimension 2


In [ ]:
# pre-built functions of Numpy
# (1). Zeros()-> it will create an array in which all the values will be 0
# in either one dimensional or multi-dimensional.
a= np.zeros(3)
a
b = np.zeros((3,4))

In [ ]:
# (2). ones()-> it will create an array in which all the values will be 1
# in either one dimensional or multi-dimensional.
a= np.ones(3)
print(a)
b = np.ones((3,4))    # two element cant go in one dimension
print(b)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
b = np.ones((5,6))
print(b.size)
print(b.shape)
print(b.ndim)

30
(5, 6)
2
